# Generated by Django 2.2.12 on 2020-05-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200519_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='web_url',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='web_url',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
