# Generated by Django 2.2.12 on 2020-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200527_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pipeline_id', models.CharField(max_length=32)),
                ('stage', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=32)),
                ('web_url', models.CharField(default='none', max_length=256)),
            ],
        ),
    ]
